library(tidyverse)
library(dplyr)
library(stringr)
library(sf)
library(modelr)
library(tidycensus)
library(httr)
library(jsonlite)
library(h)

### Census key

census_api_key("794708f156e5f9a870d2531bb80e777690f72326", install = TRUE)

### Loading Census Bureau data

# 2010 

acs2010 <- get_acs(survey = "acs1",
                   year = 2010,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     pctlessthanhs = "S1501_C01_002",
                     pcthsgrad = "S1501_C01_003",
                     pctsomecollegeassociates = "S1501_C01_004",
                     pctbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0017",
                     countwhite = "DP05_0032",
                     countblack = "DP05_0033",
                     counthispanic = "DP05_0066",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_028",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_015")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = pctlessthanhs / 100,
         prop_hs_grad = pcthsgrad / 100,
         prop_some_college_associates = pctsomecollegeassociates / 100,
         prop_bachelors_higher = pctbachhigher / 100,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2010) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2011

acs2011 <- get_acs(survey = "acs1",
                   year = 2011,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     pctlessthanhs = "S1501_C01_002",
                     pcthsgrad = "S1501_C01_003",
                     pctsomecollegeassociates = "S1501_C01_004",
                     pctbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0017",
                     countwhite = "DP05_0032",
                     countblack = "DP05_0033",
                     counthispanic = "DP05_0066",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_028",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_015")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = pctlessthanhs / 100,
         prop_hs_grad = pcthsgrad / 100,
         prop_some_college_associates = pctsomecollegeassociates / 100,
         prop_bachelors_higher = pctbachhigher / 100,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2011) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2012

acs2012 <- get_acs(survey = "acs1",
                   year = 2012,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     pctlessthanhs = "S1501_C01_002",
                     pcthsgrad = "S1501_C01_003",
                     pctsomecollegeassociates = "S1501_C01_004",
                     pctbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0017",
                     countwhite = "DP05_0032",
                     countblack = "DP05_0033",
                     counthispanic = "DP05_0066",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_028",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_015")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = pctlessthanhs / 100,
         prop_hs_grad = pcthsgrad / 100,
         prop_some_college_associates = pctsomecollegeassociates / 100,
         prop_bachelors_higher = pctbachhigher / 100,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2012) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2013

acs2013 <- get_acs(survey = "acs1",
                   year = 2013,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     pctlessthanhs = "S1501_C01_002",
                     pcthsgrad = "S1501_C01_003",
                     pctsomecollegeassociates = "S1501_C01_004",
                     pctbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0017",
                     countwhite = "DP05_0032",
                     countblack = "DP05_0033",
                     counthispanic = "DP05_0066",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_028",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_015")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = pctlessthanhs / 100,
         prop_hs_grad = pcthsgrad / 100,
         prop_some_college_associates = pctsomecollegeassociates / 100,
         prop_bachelors_higher = pctbachhigher / 100,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2013) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2014

acs2014 <- get_acs(survey = "acs1",
                   year = 2014,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     pctlessthanhs = "S1501_C01_002",
                     pcthsgrad = "S1501_C01_003",
                     pctsomecollegeassociates = "S1501_C01_004",
                     pctbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0017",
                     countwhite = "DP05_0032",
                     countblack = "DP05_0033",
                     counthispanic = "DP05_0066",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_028",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_015")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = pctlessthanhs / 100,
         prop_hs_grad = pcthsgrad / 100,
         prop_some_college_associates = pctsomecollegeassociates / 100,
         prop_bachelors_higher = pctbachhigher / 100,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2014) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2015

acs2015 <- get_acs(survey = "acs1",
                   year = 2015,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0017",
                     countwhite = "DP05_0032",
                     countblack = "DP05_0033",
                     counthispanic = "DP05_0066",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_028",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2015) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2016

acs2016 <- get_acs(survey = "acs1",
                   year = 2016,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0017",
                     countwhite = "DP05_0032",
                     countblack = "DP05_0033",
                     counthispanic = "DP05_0066",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_024",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2016) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2017

acs2017 <- get_acs(survey = "acs1",
                   year = 2017,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0018",
                     countwhite = "DP05_0037",
                     countblack = "DP05_0038",
                     counthispanic = "DP05_0071",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_024",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2017) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2018

acs2018 <- get_acs(survey = "acs1",
                   year = 2018,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0018",
                     countwhite = "DP05_0037",
                     countblack = "DP05_0038",
                     counthispanic = "DP05_0071",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_024",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2018) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2019

acs2019 <- get_acs(survey = "acs1",
                   year = 2019,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0018",
                     countwhite = "DP05_0037",
                     countblack = "DP05_0038",
                     counthispanic = "DP05_0071",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_024",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2019) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2021

acs2021 <- get_acs(survey = "acs1",
                   year = 2021,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0018",
                     countwhite = "DP05_0037",
                     countblack = "DP05_0038",
                     counthispanic = "DP05_0071",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_024",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2021) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2022

acs2022 <- get_acs(survey = "acs1",
                   year = 2022,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0018",
                     countwhite = "DP05_0037",
                     countblack = "DP05_0038",
                     counthispanic = "DP05_0071",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_024",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2022) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

# 2023

acs2023 <- get_acs(survey = "acs1",
                   year = 2023,
                   geography = "county",
                   variables = c(
                     # gini
                     gini = "B19083_001",
                     # median income by quintile
                     lowest_quintile = "B19081_001",
                     second_quintile = "B19081_002",
                     third_quintile = "B19081_003",
                     fourth_quintile = "B19081_004",
                     highest_quintile = "B19081_005",
                     top_five_percent = "B19081_006",
                     # educational attainment
                     count18to24 = "S1501_C01_001",
                     count24to34 = "S1501_C01_016",
                     count35to44 = "S1501_C01_019",
                     count45to64 = "S1501_C01_022",
                     count65over = "S1501_C01_025",
                     countlessthanhs = "S1501_C01_002",
                     counthsgrad = "S1501_C01_003",
                     countsomecollegeassociates = "S1501_C01_004",
                     countbachhigher = "S1501_C01_005",
                     # total population
                     totalpopulation = "B01003_001",
                     # demographic information
                     medianage = "DP05_0018",
                     countwhite = "DP05_0037",
                     countblack = "DP05_0038",
                     counthispanic = "DP05_0071",
                     # income
                     medianincome = "S1901_C01_012",
                     medianhhincome = "S1901_C02_012",
                     countbelowpoverty = "S1701_C02_001",
                     medianhousingcosts = "S2503_C01_024",
                     # employment
                     pop16plus = "DP03_0001",
                     countlaborforce16plus = "DP03_0002",
                     countunemployedinlaborforce16plus = "DP03_0005",
                     # immigration
                     countforeignborn = "B05002_013", 
                     countforeignborncitizen = "B05002_014",
                     countforeignbornnotcitizen= "B05002_021")) |> 
  select(!moe) |> 
  pivot_wider(names_from = variable,
              values_from = estimate) |> 
  mutate(count18over = count18to24 + count24to34 + count35to44 + count45to64 + count65over,
         prop_less_than_hs = countlessthanhs / count18to24,
         prop_hs_grad = counthsgrad / count18to24,
         prop_some_college_associates = countsomecollegeassociates / count18to24,
         prop_bachelors_higher = countbachhigher / count18to24,
         prop_18_to_24 = count18to24 / totalpopulation,
         prop_24_to_34 = count24to34 / totalpopulation,
         prop_35_to_44 = count35to44 / totalpopulation,
         prop_45_to_64 = count45to64 / totalpopulation,
         prop_65_years_older = count65over / totalpopulation,
         prop_white = countwhite / totalpopulation,
         prop_black = countblack / totalpopulation,
         prop_hispanic = counthispanic / totalpopulation,
         prop_below_poverty = countbelowpoverty / totalpopulation,
         labor_force_part_rate = countlaborforce16plus / pop16plus,
         unemployment_rate = countunemployedinlaborforce16plus / countlaborforce16plus,
         prop_foreign_born = countforeignborn / totalpopulation,
         prop_foreign_born_undocumented = countforeignbornnotcitizen / totalpopulation,
         year = 2023) |> 
  rename(median_age = medianage,
         median_income = medianincome, 
         median_housing_costs = medianhousingcosts,
         total_population = totalpopulation,
         geoid = GEOID,
         name = NAME) |> 
  select(geoid,
         name,
         year,
         gini,
         lowest_quintile,
         second_quintile,
         third_quintile,
         fourth_quintile,
         highest_quintile,
         top_five_percent,
         total_population,
         prop_less_than_hs,
         prop_hs_grad,
         prop_some_college_associates,
         prop_bachelors_higher,
         prop_18_to_24,
         prop_24_to_34,
         prop_35_to_44,
         prop_45_to_64,
         prop_65_years_older,
         prop_white,
         prop_black,
         prop_hispanic,
         prop_below_poverty,
         labor_force_part_rate,
         unemployment_rate,
         median_age,
         median_income,
         median_housing_costs,
         prop_foreign_born,
         prop_foreign_born_undocumented)

### Binding ACS Data Together 

acs_binded_counties <- rbind(acs2010, acs2011, acs2012, acs2013, acs2014, acs2015, acs2016,
                    acs2017, acs2018, acs2019, acs2021, acs2022, acs2023) |> 
  rename(statecounty_fips = geoid) |> 
  mutate(prop_less_than_hs = as.numeric(prop_less_than_hs),
         prop_hs_grad = as.numeric(prop_hs_grad),
         prop_some_college_associates = as.numeric(prop_some_college_associates),
         prop_bachelors_higher = as.numeric(prop_bachelors_higher),
         prop_18_to_24 = as.numeric(prop_18_to_24),
         prop_24_to_34 = as.numeric(prop_24_to_34),
         prop_35_to_44 = as.numeric(prop_35_to_44),
         prop_45_to_64 = as.numeric(prop_45_to_64),
         prop_65_years_older = as.numeric(prop_65_years_older),
         prop_white = as.numeric(prop_white),
         prop_black = as.numeric(prop_black),
         prop_hispanic = as.numeric(prop_hispanic),
         labor_force_part_rate = as.numeric(labor_force_part_rate),
         unemployment_rate = as.numeric(unemployment_rate),
         prop_foreign_born = as.numeric(prop_foreign_born),
         prop_foreign_born_undocumented = as.numeric(prop_foreign_born_undocumented))

### Implementing population density measures

county_land_area <- read.csv("Supplemental Data/2023_Gaz_counties_national.txt",
                             sep = "\t",
                             header = TRUE) |> 
  rename(statecounty_fips = GEOID,
         land_sqmi = ALAND_SQMI) |> 
  mutate(statecounty_fips = as.character(statecounty_fips),
         statecounty_fips = if_else(
    str_length(statecounty_fips) == 4,
    str_pad(statecounty_fips, width = 5, side = "left", pad = "0"),
    statecounty_fips))

acs_binded_counties <- acs_binded_counties |> 
  left_join(county_land_area |> 
              select(statecounty_fips, land_sqmi),
            by = "statecounty_fips") |> 
  mutate(pop_density = total_population / land_sqmi)

### Removing unnecessary dataframes

rm(list = ls()[grepl("acs20", ls())])
rm(county_land_area)

### Saving dataframe

save.image(here("Processed/county_acs.RData"))
